/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author ogled
 */
public class Effet extends javax.swing.JPanel {

    private BufferedImage effetImage;
    private model.Etat etat = null;
    
    /**
     * Creates new form Effet
     */
    public Effet() {
        initComponents();
        
        // Init du label
        updateLabels();
        
        // Mise à jour de l'image
        updateImageFile();
    }

    public model.Etat getEffet() {
        return etat;
    }

    public void setEffet(model.Etat etat) {
        this.etat = etat;
        
        // Pour l'édition dans le GUI
        firePropertyChange("effet", null, etat);
        
        // Mise à jour de l'image
        updateImageFile();
        updateLabels();
        
        // repaint de la frame
        repaint();
    }
    
    private String formatName(String str) {
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
        
    private void updateImageFile() {
        if(etat == null)
            return;
        
        try {
            effetImage = ImageIO.read(
                    getClass().getResource("/" + formatName(etat.name()) + ".png"));
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void updateLabels() {
        if(etat == model.Etat.ESTVIVANT) {
            labelNomEffet.setText("");
            labelDescriptionEffet.setText("");
            return;
        }
        labelNomEffet.setText(formatName(etat.name()));
        labelDescriptionEffet.setText(etat.toString());
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if(etat != model.Etat.ESTVIVANT)
            g.drawImage(effetImage, 0, 0, null);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomEffet = new javax.swing.JLabel();
        labelDescriptionEffet = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(160, 90));

        labelNomEffet.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelNomEffet.setForeground(java.awt.Color.black);

        labelDescriptionEffet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDescriptionEffet.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNomEffet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDescriptionEffet, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomEffet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescriptionEffet)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDescriptionEffet;
    private javax.swing.JLabel labelNomEffet;
    // End of variables declaration//GEN-END:variables
}
