/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary;

import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author emilien
 */
public class FrameTestToDelete extends javax.swing.JFrame {

    /**
     * Creates new form FrameTestToDelete
     */
    public FrameTestToDelete() {
        initComponents();
    }
    
    public void setDialog(Dialog dialog){
        this.dialog = dialog;
        diceCoursePanel.setDialog(dialog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBoard = new javax.swing.JPanel();
        jPlateau = new boundary.JPlateau();
        jPanelPlayers = new javax.swing.JPanel();
        diceCoursePanel = new boundary.DiceCoursePanel();
        infosJoueurBill = new boundary.InfosJoueur();
        infosJoueurJack = new boundary.InfosJoueur();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBoard.setLayout(new java.awt.GridLayout(1, 0));
        jPanelBoard.add(jPlateau);

        jPanelPlayers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        infosJoueurBill.setPV(5);
        infosJoueurBill.setDureeEffet(0);
        infosJoueurBill.setEffet(boundary.Effet.TypeEffet.none);
        infosJoueurBill.setJoueur(boundary.InfosJoueur.Joueur.Bill);

        infosJoueurJack.setPV(5);
        infosJoueurJack.setDureeEffet(5);
        infosJoueurJack.setEffet(boundary.Effet.TypeEffet.avalanche);
        infosJoueurJack.setJoueur(boundary.InfosJoueur.Joueur.Jack);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPlayersLayout = new javax.swing.GroupLayout(jPanelPlayers);
        jPanelPlayers.setLayout(jPanelPlayersLayout);
        jPanelPlayersLayout.setHorizontalGroup(
            jPanelPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayersLayout.createSequentialGroup()
                .addGroup(jPanelPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infosJoueurBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPlayersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infosJoueurJack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayersLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diceCoursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPlayersLayout.setVerticalGroup(
            jPanelPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infosJoueurBill, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPlayersLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton1))
                    .addGroup(jPanelPlayersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diceCoursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(infosJoueurJack, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        finDePartie("test");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTestToDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTestToDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTestToDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTestToDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTestToDelete().setVisible(true);
            }
        });
    }

    public InfosJoueur getInfosJoueurBill() {
        return infosJoueurBill;
    }

    public InfosJoueur getInfosJoueurJack() {
        return infosJoueurJack;
    }

    public JPlateau getjPlateau() {
        return jPlateau;
    }

    public DiceCoursePanel getDiceCoursePanel() {
        return diceCoursePanel;
    }
    
    public void finDePartie(String etat) {
        JDialog finWindow = new JDialog();
        finWindow.setSize(300, 150);
        finWindow.setLocationRelativeTo(null);
        Container pane = finWindow.getContentPane();
        pane.setLayout(null);
        etat = "Bill";
        String labelStr = switch (etat) {
            case "Egalité" -> "Défaite des deux joueurs !";
            default -> etat + " est victorieux !";
        };
        JLabel labelVictory = new JLabel(labelStr);
        pane.add(labelVictory);
        labelVictory.setHorizontalAlignment(JLabel.CENTER);
        labelVictory.setVerticalTextPosition(JLabel.TOP);
        
        
        JButton buttonRestart = new JButton("Recommencer");
        JButton buttonQuitter = new JButton("Quitter");
        pane.add(buttonRestart);
        pane.add(buttonQuitter);
        buttonRestart.setBounds(10, 80, 110, 25);
        buttonQuitter.setBounds(165, 80, 110, 25);
        buttonRestart.addActionListener((java.awt.event.ActionEvent e) -> {
           finWindow.dispose();
           
        });
        buttonQuitter.addActionListener((java.awt.event.ActionEvent e) -> {
            finWindow.dispose();
            this.dispose();
        });
        finWindow.setVisible(true);
        
    }

    private Dialog dialog;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.DiceCoursePanel diceCoursePanel;
    private boundary.InfosJoueur infosJoueurBill;
    private boundary.InfosJoueur infosJoueurJack;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelPlayers;
    private boundary.JPlateau jPlateau;
    // End of variables declaration//GEN-END:variables
}
