/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

/**
 *
 * @author PJR4505A
 */
public class JPlateau extends javax.swing.JPanel {

    /**
     * Creates new form JPlateau
     */
    public JPlateau() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCase7 = new boundary.PanelCase();
        panelCase8 = new boundary.PanelCase();
        panelCase10 = new boundary.PanelCase();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Case1 = new boundary.PanelCase();
        Case2 = new boundary.PanelCase();
        Case3 = new boundary.PanelCase();
        Case4 = new boundary.PanelCase();
        Case5 = new boundary.PanelCase();
        Case6 = new boundary.PanelCase();
        Case7 = new boundary.PanelCase();
        Case8 = new boundary.PanelCase();
        Case9 = new boundary.PanelCase();
        Case10 = new boundary.PanelCase();
        Case11 = new boundary.PanelCase();
        Case12 = new boundary.PanelCase();
        Case14 = new boundary.PanelCase();
        Case15 = new boundary.PanelCase();
        Case16 = new boundary.PanelCase();
        Case17 = new boundary.PanelCase();
        Case18 = new boundary.PanelCase();
        Case13 = new boundary.PanelCase();
        Case19 = new boundary.PanelCase();
        Case20 = new boundary.PanelCase();
        Case21 = new boundary.PanelCase();
        Case22 = new boundary.PanelCase();
        Case23 = new boundary.PanelCase();
        Case24 = new boundary.PanelCase();
        Case25 = new boundary.PanelCase();
        Case26 = new boundary.PanelCase();
        Case27 = new boundary.PanelCase();
        Case28 = new boundary.PanelCase();
        Case29 = new boundary.PanelCase();
        Case30 = new boundary.PanelCase();
        jPion1 = new boundary.JPion();

        javax.swing.GroupLayout panelCase7Layout = new javax.swing.GroupLayout(panelCase7);
        panelCase7.setLayout(panelCase7Layout);
        panelCase7Layout.setHorizontalGroup(
            panelCase7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCase7Layout.setVerticalGroup(
            panelCase7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCase8Layout = new javax.swing.GroupLayout(panelCase8);
        panelCase8.setLayout(panelCase8Layout);
        panelCase8Layout.setHorizontalGroup(
            panelCase8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCase8Layout.setVerticalGroup(
            panelCase8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCase10Layout = new javax.swing.GroupLayout(panelCase10);
        panelCase10.setLayout(panelCase10Layout);
        panelCase10Layout.setHorizontalGroup(
            panelCase10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCase10Layout.setVerticalGroup(
            panelCase10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayout(new java.awt.GridLayout(6, 5));

        javax.swing.GroupLayout Case1Layout = new javax.swing.GroupLayout(Case1);
        Case1.setLayout(Case1Layout);
        Case1Layout.setHorizontalGroup(
            Case1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case1Layout.setVerticalGroup(
            Case1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case1);

        javax.swing.GroupLayout Case2Layout = new javax.swing.GroupLayout(Case2);
        Case2.setLayout(Case2Layout);
        Case2Layout.setHorizontalGroup(
            Case2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case2Layout.setVerticalGroup(
            Case2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case2);

        javax.swing.GroupLayout Case3Layout = new javax.swing.GroupLayout(Case3);
        Case3.setLayout(Case3Layout);
        Case3Layout.setHorizontalGroup(
            Case3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case3Layout.setVerticalGroup(
            Case3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case3);

        javax.swing.GroupLayout Case4Layout = new javax.swing.GroupLayout(Case4);
        Case4.setLayout(Case4Layout);
        Case4Layout.setHorizontalGroup(
            Case4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case4Layout.setVerticalGroup(
            Case4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case4);

        javax.swing.GroupLayout Case5Layout = new javax.swing.GroupLayout(Case5);
        Case5.setLayout(Case5Layout);
        Case5Layout.setHorizontalGroup(
            Case5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case5Layout.setVerticalGroup(
            Case5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case5);

        javax.swing.GroupLayout Case6Layout = new javax.swing.GroupLayout(Case6);
        Case6.setLayout(Case6Layout);
        Case6Layout.setHorizontalGroup(
            Case6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case6Layout.setVerticalGroup(
            Case6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case6);

        javax.swing.GroupLayout Case7Layout = new javax.swing.GroupLayout(Case7);
        Case7.setLayout(Case7Layout);
        Case7Layout.setHorizontalGroup(
            Case7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case7Layout.setVerticalGroup(
            Case7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case7);

        javax.swing.GroupLayout Case8Layout = new javax.swing.GroupLayout(Case8);
        Case8.setLayout(Case8Layout);
        Case8Layout.setHorizontalGroup(
            Case8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case8Layout.setVerticalGroup(
            Case8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case8);

        javax.swing.GroupLayout Case9Layout = new javax.swing.GroupLayout(Case9);
        Case9.setLayout(Case9Layout);
        Case9Layout.setHorizontalGroup(
            Case9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case9Layout.setVerticalGroup(
            Case9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case9);

        javax.swing.GroupLayout Case10Layout = new javax.swing.GroupLayout(Case10);
        Case10.setLayout(Case10Layout);
        Case10Layout.setHorizontalGroup(
            Case10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case10Layout.setVerticalGroup(
            Case10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case10);

        javax.swing.GroupLayout Case11Layout = new javax.swing.GroupLayout(Case11);
        Case11.setLayout(Case11Layout);
        Case11Layout.setHorizontalGroup(
            Case11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case11Layout.setVerticalGroup(
            Case11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case11);

        javax.swing.GroupLayout Case12Layout = new javax.swing.GroupLayout(Case12);
        Case12.setLayout(Case12Layout);
        Case12Layout.setHorizontalGroup(
            Case12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case12Layout.setVerticalGroup(
            Case12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case12);

        javax.swing.GroupLayout Case14Layout = new javax.swing.GroupLayout(Case14);
        Case14.setLayout(Case14Layout);
        Case14Layout.setHorizontalGroup(
            Case14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case14Layout.setVerticalGroup(
            Case14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case14);

        javax.swing.GroupLayout Case15Layout = new javax.swing.GroupLayout(Case15);
        Case15.setLayout(Case15Layout);
        Case15Layout.setHorizontalGroup(
            Case15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case15Layout.setVerticalGroup(
            Case15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case15);

        javax.swing.GroupLayout Case16Layout = new javax.swing.GroupLayout(Case16);
        Case16.setLayout(Case16Layout);
        Case16Layout.setHorizontalGroup(
            Case16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case16Layout.setVerticalGroup(
            Case16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case16);

        javax.swing.GroupLayout Case17Layout = new javax.swing.GroupLayout(Case17);
        Case17.setLayout(Case17Layout);
        Case17Layout.setHorizontalGroup(
            Case17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case17Layout.setVerticalGroup(
            Case17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case17);

        javax.swing.GroupLayout Case18Layout = new javax.swing.GroupLayout(Case18);
        Case18.setLayout(Case18Layout);
        Case18Layout.setHorizontalGroup(
            Case18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case18Layout.setVerticalGroup(
            Case18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case18);

        javax.swing.GroupLayout Case13Layout = new javax.swing.GroupLayout(Case13);
        Case13.setLayout(Case13Layout);
        Case13Layout.setHorizontalGroup(
            Case13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case13Layout.setVerticalGroup(
            Case13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case13);

        javax.swing.GroupLayout Case19Layout = new javax.swing.GroupLayout(Case19);
        Case19.setLayout(Case19Layout);
        Case19Layout.setHorizontalGroup(
            Case19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case19Layout.setVerticalGroup(
            Case19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case19);

        javax.swing.GroupLayout Case20Layout = new javax.swing.GroupLayout(Case20);
        Case20.setLayout(Case20Layout);
        Case20Layout.setHorizontalGroup(
            Case20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case20Layout.setVerticalGroup(
            Case20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case20);

        javax.swing.GroupLayout Case21Layout = new javax.swing.GroupLayout(Case21);
        Case21.setLayout(Case21Layout);
        Case21Layout.setHorizontalGroup(
            Case21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case21Layout.setVerticalGroup(
            Case21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case21);

        javax.swing.GroupLayout Case22Layout = new javax.swing.GroupLayout(Case22);
        Case22.setLayout(Case22Layout);
        Case22Layout.setHorizontalGroup(
            Case22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case22Layout.setVerticalGroup(
            Case22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case22);

        javax.swing.GroupLayout Case23Layout = new javax.swing.GroupLayout(Case23);
        Case23.setLayout(Case23Layout);
        Case23Layout.setHorizontalGroup(
            Case23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case23Layout.setVerticalGroup(
            Case23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case23);

        javax.swing.GroupLayout Case24Layout = new javax.swing.GroupLayout(Case24);
        Case24.setLayout(Case24Layout);
        Case24Layout.setHorizontalGroup(
            Case24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case24Layout.setVerticalGroup(
            Case24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case24);

        javax.swing.GroupLayout Case25Layout = new javax.swing.GroupLayout(Case25);
        Case25.setLayout(Case25Layout);
        Case25Layout.setHorizontalGroup(
            Case25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case25Layout.setVerticalGroup(
            Case25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case25);

        javax.swing.GroupLayout Case26Layout = new javax.swing.GroupLayout(Case26);
        Case26.setLayout(Case26Layout);
        Case26Layout.setHorizontalGroup(
            Case26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case26Layout.setVerticalGroup(
            Case26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case26);

        javax.swing.GroupLayout Case27Layout = new javax.swing.GroupLayout(Case27);
        Case27.setLayout(Case27Layout);
        Case27Layout.setHorizontalGroup(
            Case27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case27Layout.setVerticalGroup(
            Case27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case27);

        javax.swing.GroupLayout Case28Layout = new javax.swing.GroupLayout(Case28);
        Case28.setLayout(Case28Layout);
        Case28Layout.setHorizontalGroup(
            Case28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case28Layout.setVerticalGroup(
            Case28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case28);

        javax.swing.GroupLayout Case29Layout = new javax.swing.GroupLayout(Case29);
        Case29.setLayout(Case29Layout);
        Case29Layout.setHorizontalGroup(
            Case29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case29Layout.setVerticalGroup(
            Case29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case29);

        javax.swing.GroupLayout Case30Layout = new javax.swing.GroupLayout(Case30);
        Case30.setLayout(Case30Layout);
        Case30Layout.setHorizontalGroup(
            Case30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        Case30Layout.setVerticalGroup(
            Case30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Case30);

        jPion1.setBackground(new java.awt.Color(255, 255, 255));
        jPion1.setPathProperty("12.png");

        javax.swing.GroupLayout jPion1Layout = new javax.swing.GroupLayout(jPion1);
        jPion1.setLayout(jPion1Layout);
        jPion1Layout.setHorizontalGroup(
            jPion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPion1Layout.setVerticalGroup(
            jPion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(279, 279, 279)
                    .addComponent(jPion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(320, 320, 320)
                    .addComponent(jPion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(320, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.PanelCase Case1;
    private boundary.PanelCase Case10;
    private boundary.PanelCase Case11;
    private boundary.PanelCase Case12;
    private boundary.PanelCase Case13;
    private boundary.PanelCase Case14;
    private boundary.PanelCase Case15;
    private boundary.PanelCase Case16;
    private boundary.PanelCase Case17;
    private boundary.PanelCase Case18;
    private boundary.PanelCase Case19;
    private boundary.PanelCase Case2;
    private boundary.PanelCase Case20;
    private boundary.PanelCase Case21;
    private boundary.PanelCase Case22;
    private boundary.PanelCase Case23;
    private boundary.PanelCase Case24;
    private boundary.PanelCase Case25;
    private boundary.PanelCase Case26;
    private boundary.PanelCase Case27;
    private boundary.PanelCase Case28;
    private boundary.PanelCase Case29;
    private boundary.PanelCase Case3;
    private boundary.PanelCase Case30;
    private boundary.PanelCase Case4;
    private boundary.PanelCase Case5;
    private boundary.PanelCase Case6;
    private boundary.PanelCase Case7;
    private boundary.PanelCase Case8;
    private boundary.PanelCase Case9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private boundary.JPion jPion1;
    private boundary.PanelCase panelCase10;
    private boundary.PanelCase panelCase7;
    private boundary.PanelCase panelCase8;
    // End of variables declaration//GEN-END:variables
}
