/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

/**
 *
 * @author Megaport
 */
public class PanelInfosJoueur extends javax.swing.JPanel {

    public enum Joueur {Bill, Jack};
    private Joueur joueur = Joueur.Bill;
    private boolean turn = true;
    
    /**
     * Creates new form PanelInfosJoueur
     */
    public PanelInfosJoueur() {
        initComponents();
    }

    public void setJoueur(PanelInfosJoueur.Joueur joueur) {
        this.joueur = joueur;

        // Pour l'édition dans le GUI
        firePropertyChange("joueur", null, joueur);

        // On mets à jour les images
        this.background.setAlternative(joueur == PanelInfosJoueur.Joueur.Jack);
        this.pointsVie.setAlternative(joueur == PanelInfosJoueur.Joueur.Jack);
    }
    
    public int getPV() {
        return this.pointsVie.getNombrePV();
    }
    
    public void setPV(int PV) {
        this.pointsVie.setNombrePV(PV);

        // Pour l'édition dans le GUI
        firePropertyChange("PV", null, PV);
    }

    public void setEtat(model.Etat etat) {
        this.effet.setEffet(etat);

        // Pour l'édition dans le GUI
        firePropertyChange("etat", null, effet);
    }

    public void setTurn(boolean turn) {
        this.turn = turn;
        panelTurn.setVisible(turn);
        firePropertyChange("turn", null, turn);
    }

    public boolean getTurn() {
        return turn;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        effet1 = new boundary.Effet();
        background = new boundary.IconJoueur();
        pointsVie = new boundary.barreDeVie();
        effet = new boundary.Effet();
        jPanel1 = new javax.swing.JPanel();
        panelTurn = new boundary.PanelTurn();

        background.setX2Res(true);

        pointsVie.setNombrePV(5);

        javax.swing.GroupLayout pointsVieLayout = new javax.swing.GroupLayout(pointsVie);
        pointsVie.setLayout(pointsVieLayout);
        pointsVieLayout.setHorizontalGroup(
            pointsVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        pointsVieLayout.setVerticalGroup(
            pointsVieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointsVie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(effet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(pointsVie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(effet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelTurn.setPathTurn("Green_Arrow_Right.png");

        javax.swing.GroupLayout panelTurnLayout = new javax.swing.GroupLayout(panelTurn);
        panelTurn.setLayout(panelTurnLayout);
        panelTurnLayout.setHorizontalGroup(
            panelTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        panelTurnLayout.setVerticalGroup(
            panelTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(panelTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private boundary.IconJoueur background;
    private boundary.Effet effet;
    private boundary.Effet effet1;
    private javax.swing.JPanel jPanel1;
    private boundary.PanelTurn panelTurn;
    private boundary.barreDeVie pointsVie;
    // End of variables declaration//GEN-END:variables
}
